#
# Copyright (c) 2024 - 2025 Ping Identity Corporation. All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

name: Build and Test
on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      head_sha:
        description: Head commit SHA to check out
        type: string
      head_repo:
        description: Head repository to check out
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: Slack Notifier Incoming Webhook
        required: true
      CODECOV_TOKEN:
        description: Codecov token
        required: true
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Clone the repo
      - name: Clone the repository
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.head_sha || github.event.pull_request.head.sha }}
          repository: ${{ inputs.head_repo || github.event.pull_request.head.repo.full_name }}
          persist-credentials: false

      # Setup JDK and cache and restore dependencies.
      - name: Setup JDK 17
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Execute all unit tests from all modules
      - name: Execute unit tests
        run: |
          ./gradlew --rerun-tasks testDebugUnitTestCoverage --stacktrace --no-daemon

      # Publish test reports for the unit tests
      # dorny/test-reporter needs checks:write which is unavailable for fork PRs
      - name: Publish test results
        if: (success() || failure()) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: dorny/test-reporter@v3
        with:
          name: Unit tests results
          path: '**/build/test-results/**/TEST-*.xml'
          list-suites: 'all'
          list-tests: 'failed'
          fail-on-error: 'true'
          fail-on-empty: 'true'
          reporter: java-junit

      - name: Upload Android Test Report (HTML)
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: unit-tests-report
          path: '**/build/reports/tests/testDebugUnitTest/**'

      # Collect all coverage report files
      - name: Find all coverage report files from all modules
        run: |
          echo "COVERAGE_REPORTS=$(echo $(printf '%s,' $(find . | grep test-coverage.xml)))" >> $GITHUB_ENV

      # Upload code coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.COVERAGE_REPORTS }}
          flags: unit-tests

      - uses: 8398a7/action-slack@v3
        with:
          mention: 'stoyan.petrov,andy.witrisna'
          if_mention: 'failure,cancelled'
          fields: repo,author,eventName,message,job,pullRequest,took
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)